USE [master]
GO

/****** Object:  Database [Förening]    Script Date: 2018-04-05 13:08:34 ******/
CREATE DATABASE [Förening]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Förening', FILENAME = N'C:\Users\Arvid\Förening.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Förening_log', FILENAME = N'C:\Users\Arvid\Förening_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Förening] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Förening].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Förening] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Förening] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Förening] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Förening] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Förening] SET ARITHABORT OFF 
GO

ALTER DATABASE [Förening] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Förening] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Förening] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Förening] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Förening] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Förening] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Förening] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Förening] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Förening] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Förening] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Förening] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Förening] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Förening] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Förening] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Förening] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Förening] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Förening] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Förening] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Förening] SET  MULTI_USER 
GO

ALTER DATABASE [Förening] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Förening] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Förening] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Förening] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Förening] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Förening] SET QUERY_STORE = OFF
GO

USE [Förening]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Förening] SET  READ_WRITE 
GO

